stages:
  - test
  - build
  - deploy

variables:
  NODE_ENV: production
  PORT: $PORT
  HOST: $HOST
  DB_HOST: $DB_HOST
  DB_PORT: $DB_PORT
  DB_USER: $DB_USER
  DB_PASSWORD: $DB_PASSWORD
  DB_NAME: $DB_NAME
  JWT_SECRET: $JWT_SECRET
  LOG_LEVEL: $LOG_LEVEL

test:
  stage: test
  image: node:20
  before_script:
    - npm install
  script:
    - npm test
  artifacts:
    paths:
      - test-results.xml
    expire_in: 1 week

build:
  stage: build
  image: node:20
  dependencies:
    - test
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 1 week

deploy:
  stage: deploy
  image: node:20
  dependencies:
    - build
  environment:
    name: production
    url: https://your-netlify-site.netlify.app
  script:
    - npm install netlify-cli -g
    - npx netlify deploy --prod --dir=dist --auth=$NETLIFY_AUTH_TOKEN --site=$NETLIFY_SITE_ID
  only:
    - main